Log sleeper when host-session fails
Handy for cleanly terminating the session after investigation. This
method of killing will ensure cleanup for persistent or untrusted
targets.

Change-Id: I97908f973e35517696b7d9d05c28e71f16aec41f

diff --git a/config/bench/lava/host-session b/config/bench/lava/host-session
--- a/config/bench/lava/host-session
+++ b/config/bench/lava/host-session
@@ -58,7 +58,14 @@ function exitfunc {
                   #most information to the user about flags they might need
       fi
       ssh_rune --
-      sleep infinity
+      sleep infinity&
+      if test -d "${maindir}/data"; then
+        echo $! > "${maindir}/data/sleeper"
+      else
+        echo "${maindir}/data not ready, cannot record PID of sleeper" >&2
+        echo "PID is $!" >&2
+      fi
+      wait $! || true #'|| true' -- don't terminate here if the sleeper is killed, want to do the cleanup
     fi
   fi
   if test x"${tmpdir:-}" != x; then
