Sanity check location when running trusted
This only affects LAVA, which is the only place where the 'trusted'
concept applies. Check is there to reduce chance of user error
publishing results in an internet-facing LAVA instance.

Change-Id: I94107065c5365fde30a653d1c8724f7244bb5f32

diff --git a/config/bench/lava/host-session b/config/bench/lava/host-session
--- a/config/bench/lava/host-session
+++ b/config/bench/lava/host-session
@@ -50,7 +50,19 @@ fi
 if test x"$8" = xNone; then
   trusted=0
 elif test x"$8" = xTrusted; then
-  trusted=1
+  trusted=0
+  for i in 1 2 3 4 5; do
+    if ping -q -c 1 -t 1 lava.tcwglab; then
+      trusted=1
+      break
+    fi
+  done
+  if test ${trusted} -eq 0; then
+    echo "Trusted set in YAML but either:" >&2
+    echo "lava.tcwglab is more than 1 hop away" >&2
+    echo "lava.tcwglab could not be found in 5 pings" >&2
+    exit 1
+  fi
 else
   echo "Bad value '$8' for TRUST" >&2
   exit 1
